name: 'Prepare Example app'
description: 'Does necessary pre-work for the example app to compile natively'

inputs:
  app-dir:
    description: 'Path to the example app directory'
    required: false
    default: './example-app'

runs:
  using: 'composite'
  steps:
    - name: 'Build plugin'
      working-directory: ./plugin
      shell: bash
      run: pnpm run build
    - name: 'Build Web example app'
      working-directory: ${{ inputs.app-dir }}
      shell: bash
      run: pnpm run build
    - name: 'Sync example app native platforms'
      working-directory: ${{ inputs.app-dir }}
      shell: bash
      run: pnpm exec cap sync
