name: "Basic Tests"

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml

  lint-test:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint-packages.yml

  verify-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_verify-packages.yml

  build-example-app-android:
    needs: ['verify-packages']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Prepare example app'
        uses: ./.github/actions/prepare-example-app
      - name: 'Build Android example app'
        working-directory: ./example-app/android
        run: ./gradlew clean assembleDebug

  build-example-app-ios:
    needs: ['verify-packages']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Prepare example app'
        uses: ./.github/actions/prepare-example-app
      - name: 'Build iOS example app'
        working-directory: ./example-app/ios/App
        run: xcodebuild clean build -workspace App.xcworkspace -scheme App CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  build-example-app-spm-ios:
    needs: ['verify-packages']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Prepare example app'
        uses: ./.github/actions/prepare-example-app
        with:
          app-dir: './example-app-spm'
      - name: 'Build iOS SPM example app'
        working-directory: ./example-app-spm/ios/App
        run: xcodebuild clean build -project App.xcodeproj -scheme App CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
