name: Release Dev Build for PR

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  id-token: write

jobs:
  release-dev-of-plugins:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: "NPM Identity"
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc
          npm whoami

      - name: Version & Publish
        env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: | 
          npm whoami
          npm version prerelease --no-git-tag-version -f --preid dev-$PR_NUMBER-$(date +%Y%m%dT%H%M%S)
          npm publish --tag dev
        working-directory: ./plugin

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./plugin
          
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Released dev build of Google Maps with dev version: ${{ steps.package-version.outputs.current-version }}
