name: "Release from Prerelease"

on: workflow_dispatch

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm-latest-from-pre:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: "NPM Identity"
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc
          npm whoami
          
      - name: "Git Config"
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"

      - name: Version & Publish
        env: 
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
        run: |
          pnpm run ci:publish:latest-from-pre
