name: "Lint Packages"

on: 
  workflow_call:
    secrets:
      CAP_GH_RELEASE_TOKEN:
        required: true

jobs:
  lint:
    runs-on: 'macos-14'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: 'Lint Packages'
        shell: bash
        run: |
          pnpm run lint
